USE codeup_test_db;
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('﻿Michael Jackson','Thriller','1982','47.3','"Pop rock R&B"');
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('Eagles','Their Greatest Hits (1971–1975)','1976','41.2','"Country rock soft rock folk rock"');
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('AC/DC','Back in Black','1980','26.1','Hard rock');
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('Pink Floyd','The Dark Side of the Moon','1973','24.2','Progressive rock');
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('Whitney Houston / Various artists','The Bodyguard','1992','28.4','"R&B soul pop soundtrack"');
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('Meat Loaf','Bat Out of Hell','1977','21.5','"Hard rock glam rock heavy metal"');
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('Eagles','Hotel California','1976','31.5','Soft rock');
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('Bee Gees / Various artists','Saturday Night Fever','1977','21.6','Disco');
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('Fleetwood Mac','Rumours','1977','27.9','Soft rock');
INSERT INTO albums (artist, name, release_date, sales, genre) VALUES ('Shania Twain','Come On Over','1997','29.6','"Country pop"');
